### ISSUE TITLE
[feature request] Hiding reservation details from non-staff users (username, etc)

### ISSUE THREAD

**Issue by r-xyz** [usnistgov/NEMO#121]
Hello,
Thanks for such a useful tool.
A useful feature might be an option to hide reservation details (or at least to add the possibility to hide the User personal data) in the calendar view for non-staff users.
This would help adoption especially in scenarios with strict User Data Protection Policy, to avoid exposing user Personal Data among users if required.
I would be happy to help implementing it, so I am opening this issue to discuss at which level would make more sense to implement it.

1. Global administration settings which affect the behavior over the whole user base.
2. User-level setting (with possibility to set a default) to let the user choose.
3. Combination of both, with admin setting consisting of the following options:
  a. Hide all (Details always hidden, user choice disabled)
  b. User choice (Visibility based on user choice, with default set)
  c. Show all (Details always shown, user choice disabled)

Of course, first choice seems the less complex to implement and probably already achieving the MVP, but I would appreciate some feedback.

Thanks in advance!

**Comment by rptmat57** [comment]
This is an interesting idea, and it would be good to see if other labs would find this useful.
At NIST, we do want some level of information displayed (like first & last name or username) which helps users in the lab know who is qualified, using a tool regularly, or before/after them etc. and promote discussions between lab members.
There aren't a lot of personal details stored in NEMO (no phone number, mailing address etc.) and the email address isn't displayed anywhere.

That being said, I am sure there are very strict User Data Protection Policies in some labs and such a feature could be helpful in those cases.

A couple of things (unordered) off the top of my head:

1. Staff info should not be hidden (applies to tool superusers as well)
2. Staff and any other elevated position should be able to see user information at all times
3. Are there situations where the user information should be always displayed? (Problem reports visible in tool control, when requesting Temporary access and looking up buddies, when creating a buddy request/replies for example) I think if the user posts anything publicly (Buddy request or reply to request) it should show their names.
4. Places to look into: Calendar, Tool comments/reports, Status dashboard, Jumbotron, Occupancy (Kiosk & Area access), Kiosk tool info
5. It _could_ slow some pages down due to checking settings/preferences every time

Implementation-wise, it will all depend on the request.user (since depending on who is looking at the page, the info would be different). Could probably be done with a custom tag, something like: `{% user_display user %}` for default user display and `{% user_display user username|first_name|last_name %}` for displaying specific attributes.

option 3 would offer the most flexibility and would be my first choice, otherwise I prefer option 2, for the reason I highlighted at the start of the post (promoting discussion etc among users)

This is my personal opinion and thoughts, but I will bring it to my supervisor for consideration at our next meeting.

The possible outcomes are:

1. NIST takes on the development of the feature
2. NIST would accept PR for this feature
3. NIST doesn't see the value/need for this feature

**Comment by r-xyz** [comment]
Thanks for considering it and for the constructive feedback!
I agree showing reservation details can promote constructive discussions and I really appreciate the fact that NEMO only requires a bare minimum of personal data.
Regarding your comments, I agree with the points you made. Maybe just a bit worried about the impact of # 5 (slowing down).

[Slightly OT] The idea came up due to our current setup: in our lab door access is controlled externally by the building manager, though we are implementing internal kiosks with readers. We then need to keep track of two badge data type: the ID we are able to read and the "building badge number" we need to communicate to building manager for changes. As a solution, we thought of setting `username` as the latter number, but sharing it between users would not be desirable.

If choosing option 3, it might be interesting to still force hiding the username. Alternatively - and if it makes sense for NIST-, I might submit a different PR adding an extra column to the user DB table (kind of a `notes` field). I would like to take the chance to also ask which option would have less impact on the overall performance and code maintenance.
[/Slightly OT]

**Comment by rptmat57** [comment]
Knowing your setup and actual issue is really helpful. Using username for that purpose is probably not the way you want to go, since usernames are also used for login.
 
There have been others inquiring about adding more information to users, and I think I like your idea of a `notes` field the best. I would make it a TextField, and this way it could be used to store any kind of information. for example, facilities could use it to store phone number, mailing address, emergency contact etc.
This option would be by far the least impactful and very likely to be accepted.
We might even do it ourselves, since it would only take a few minutes. I will keep you posted on Tuesday after meeting with my supervisor.

**Comment by rptmat57** [comment]
User `notes` will be available in the next release of NEMO

**Comment by r-xyz** [comment]
Thanks for useful feature and for update!
I already had a look to the commit, looking forward for the next release!
