### ISSUE TITLE
Rendering of '/safety/' fails when 'admin' module not present and logged as superuser

### ISSUE THREAD

**Issue by r-xyz** [usnistgov/NEMO#135]
Not sure what is the best approach to fix this, so I open an issue.
When running an instance with admin interface disabled, a superuser will get an internal error ('NoReverseMatch') if no safety items are present.
Clicking on the Safety menu (`/safety/`) will fail when rendering `safety.html` due to a missing check on the `admin`of the url on this line:
https://github.com/usnistgov/NEMO/blob/d9d0fc8c82ab0239fc9d130c4873c83e026525db/NEMO/templates/safety/safety.html#L46
Easy solution should be adding a function to check if `admin` site is enabled on `usage.py` view, though I am not sure if this is an issue which might be shared by other templates and might require a more generic mitigation.

PS: I also take the chance to ask if PRs that addresses bugs should usually be made against `master` or against the next minor release (i.e. `4.5.0-dev`).
Thanks

**Comment by rptmat57** [comment]
For PR target branches, unless it's a really big blocking issue, it should be made against the current dev branch.
I will check anyway and move it to the appropriate branch, so it's not a huge deal.

I am aware of the issue you are mentioning and there are actually a couple places where it's a problem. I will add a check in the templates.
I am working on it and it will be fixed in the next version of NEMO. Thankfully it only happens for superusers.
In this specific case you can hide that tab in the Customization -> Safety page, so that it won't show at all and you can re-enable it after you add stuff in it. Not ideal, but a workaround
