### ISSUE TITLE
[Feature Request] Add Date to Status Dashboard

### ISSUE THREAD

**Issue by rmwhite85** [usnistgov/NEMO#159]
The status/occupancy dashboard (located at /status_dashboard/) has a "Since" column that lists (for example "Thursday @ 6:20 PM" as the occupancy timeframe).

This makes it difficult (at a glance) for managers to know when someone just forgot to log out of a tool or area.

This request is to add the MM/DD date to the "Since" column, so it would read "Thursday 7/27 @ 6:20 PM." This way facility/lab/instrument managers can quickly locate someone who has been logged in too long (accidentally) and contact them to adjust their reservation.

The date format in MM/DD/YYYY would also be fine, but it seems unlikely that the year is necessary.

**Comment by rptmat57** [comment]
Thank you, this is something I have been thinking about as well, especially looking at the demo website where there is really no telling how long people have been logged in (I think the captain user has been logged in for years).

Since the current (hardcoded) format works with any locale/international format, we would want to keep it that way.
If someone uses NEMO with DD/MM as it is the case in other countries, we want to be careful to make this configurable.

I did some research, and I am thinking about using the Django "MONTH_DAY_FORMAT" preset format which can be customized in settings just like the other date formats.

The result would be "[DAY] [MONTH_DAY_FORMAT] @ [TIME_FORMAT]" and would be displayed in occupancy, tool status and jumbotron.

Looking into implementing this in the next version (4.7.0)
