### ISSUE TITLE
Schedule an outage

### ISSUE THREAD

**Issue by wcdyang** [usnistgov/NEMO#171]
The "schedule an outage" function in the calendar does not seem to allow for manually putting in the start and end times similar to the pop-up window when scheduling an experiment, or the function to change any information after the outage is scheduled. This limits the ability to schedule an outage across a weekend, of which the Sunday is located in the next week's view. Thanks for considering adding the function.

**Comment by rptmat57** [comment]
Hi, since NEMO 4.7.0 you can update the title and details of the outage.
You are correct that currently the dates cannot be changed after it is created. I will look into it.

There is somewhat of a workaround, if you are an admin you can go to detailed administration and change the dates directly, and alternatively you could change the first day of the week to be Monday in Customization -> Calendar

**Comment by rptmat57** [comment]
It will be fixed in version 5.1.0

**Comment by rptmat57** [comment]
This was added in NEMO 5.1.0
