### ISSUE TITLE
Landing page link naming consistency

### ISSUE THREAD

**Issue by massey21** [usnistgov/NEMO#174]
When changing the name of landing page links under Detailed Administration (e.g., changing "Calendar" to "Reservations"), it changes the name on the large icon, but it does not change the corresponding name on the Calendar link on the top toolbar that links to the same place.  Can these be brought into consistency, so that if the name changes in one place it also changes in the other?  The same thing applies to "Tool control," "Status dashboard," and "Safety" links located both in the top toolbar and as large icons.  Thanks.

**Comment by rptmat57** [comment]
This unfortunately can't be done (at least not easily) due to the nature (and flexibility) of the landing page items and the inflexibility of the toolbar.
What might be possible, however, is adding a few customization settings to update the main toolbar items.
This would allow to change the display name of each of the main toolbar items, and the admin could make sure it matches the landing page item.
If anyone is interested in submitting a Pull Request for this, please go ahead

**Comment by massey21** [comment]
Customization to edit these would be just as good!  Thank you.

Does "anyone interested in submitting a pull request" refer specifically to contributing developers, or is there some action needed from me?  I can read code, but wise people don't let me write it.

**Comment by rptmat57** [comment]
Yes, that would be a call to contributing developers, if anyone wants to take a crack at it

**Comment by rptmat57** [comment]
This was added in NEMO 5.1.0
