### ISSUE TITLE
Installation for development on Ubuntu 17.10

### ISSUE THREAD

**Issue by hwagit** [usnistgov/NEMO#4]
Hi Dylan,

I am part of an electron microscopy group in Norway interested in using your software, but I'm having problems setting it up on Ubuntu 17.10 using Docker 1.13.1 and following your instructions on the wiki pages *Installation with Docker* and *Development & test settings.py*.

First i naively try:

```bash
sudo docker run --publish 8000:8000 dylanklomparens/nemo
```

and get the error ([...] indicate blocks of text)

```bash
[...]
  File "/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but 
settings are not configured. You must either define the environment variable 
DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

What I do next:
1. Create directories (`/email`, `/media`, `/secrets` within `/nemo`) and files (`django_secret_key.txt` within `/secrets`, and `settings.py` and `sqlite.db` within `/nemo`) as per *Development & test settings.py*, however not in my root dir, but in my local user dir as `/home/<username>/nemo/`.
2. `django_secret_key.txt` is left empty.
3. Edit the following lines in the `settings.py` file you provide (original lines commented out) to point Django to the (presumably) correct places:

```python
[...]

import os

# To avoid hard coding paths. If settings.py is in /home/<username>/nemo/, then
# BASE_DIR is the string '/home/<username>/nemo/'
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

[...]

#EMAIL_FILE_PATH = '/nemo/email'
EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'email')

[...]

                #'NAME': '/nemo/sqlite.db',
                'NAME': os.path.join(BASE_DIR, 'sqlite.db'),

[...]

#STATIC_ROOT = '/nemo/static'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
#MEDIA_ROOT = '/nemo/media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

[...]

#SECRET_KEY = get_file_contents('/nemo/secrets/django_secret_key.txt')
# An arbitrary example secret key
SECRET_KEY = 'zek$#1$0@(i$t5(q*ne-r$s29#yhe9)!g$y9vc_-th4*0dxfi4'

[...]
```

4. Run the following (with `<username>` equal to my local username, note the use of `sudo`):

```bash
sudo docker run --publish 8000:8000 \
  --volume /home/<username>/nemo/settings.py:/root/NEMO/settings.py \
  --env "PYTHONPATH=/root/NEMO" \
  --env "DJANGO_SETTINGS_MODULE=settings" \
  dylanklomparens/nemo
```

and get

```bash
[...]

Migrations for 'NEMO':
  usr/lib/python3.6/site-packages/NEMO/migrations/0001_initial.py
    - Create model Account
    - Create model ActivityHistory

[...]

Operations to perform:
  Apply all migrations: NEMO, admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK

[...]

Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/fonts/
glyphicons-halflings-regular.woff2'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/fonts/
glyphicons-halflings-regular.eot'

136 static files copied to '/nemo/static'.
[2018-01-24 16:05:11 +0000] [20] [INFO] Starting gunicorn 19.7.1
[2018-01-24 16:05:11 +0000] [20] [INFO] Listening at: http://127.0.0.1:8000 (20)
[2018-01-24 16:05:11 +0000] [20] [INFO] Using worker: sync
[2018-01-24 16:05:11 +0000] [23] [INFO] Booting worker with pid: 23
```

5. Check [http://localhost:8000](http://localhost:8000), but nothing is there, and I conclude that I must have done something/a lot of things wrong.

I am unfortunately unexperienced with Docker, but have used Django off and on for three years.

A few questions:
- Am I to leave `django_secret_key.txt` empty?
- Is the settings file refered to while calling docker, `/home/user/settings.py` the same as created locally in the `/nemo` dir as per *Development & test settings.py*, which in my case is `/home/<username>/nemo/settings.py`?
- Do I need to download the online repo and point to it somehow for NEMO to work with Docker locally?

Thank you in advance, looking forward to hear from you!

**Comment by dylan-klomparens** [comment]
Hi Håkon,

I'm glad to hear you're trying out NEMO! I'll try to answer your questions best I can. Your description has already given me some good information for improvements to NEMO.

It looks like you are successfully running NEMO. There are some things you may need to do in order to access it. To answer your questions first:

> Am I to leave `django_secret_key.txt` empty?

In your `settings.py` file, I see you have a value set for `SECRET_KEY`, so you will **not** need a `django_secret_key.txt` file. Please note that by posting it on GitHub, it is no longer secret. If you plan to use NEMO in production, I highly recommend you change your secret key. You can generate a new one on the command line using `nemo generate_secret_key`.

> Is the settings file referred to while calling Docker, `/home/user/settings.py` the same as created locally in the `/nemo` dir as per _Development & test settings.py_, which in my case is `/home/<username>/nemo/settings.py`?

I think the answer is yes. You have to provide the `settings.py` file to the Docker container... it does not come packaged with one. So, since your `docker run ...` output is normal (and successfully running NEMO), it appears it's seeing your `settings.py` file correctly.

> Do I need to download the online repo and point to it somehow for NEMO to work with Docker locally?

I don't think I understand the question, because I'm not sure what you mean by "online repo". The Docker image is downloaded from Docker Hub, using the `docker run` command. However, everything else (such as `settings.py`) should be created by you.

---

Some other things you may need to do in order to access NEMO:

Several people have told me they have trouble getting NEMO to authenticate properly against an LDAP server. Any LDAP authentication errors are output as exceptions in NEMO, and the exceptions can be logged to a file. So, you can see the exact issue if logging is configured in `settings.py`. Below is an example logging configuration file that is recommended for production settings. You can open the “django error.log” to see the exception.

```
LOGGING = {
     'version': 1,
     'disable_existing_loggers': False,
     'handlers': {
           'mail_admins': {
                'level': 'INFO',
                'class': 'django.utils.log.AdminEmailHandler'
           },
           'error_file': {
                'level': 'WARNING',
                'class': 'logging.FileHandler',
                'filename': '/home/nemo/logs/django_error.log'
           },
           'security_file': {
                'level': 'INFO',
                'class': 'logging.FileHandler',
                'filename': '/home/nemo/logs/django_security.log'
           },
     },
     'loggers': {
           'django.request': {
                'handlers': ['mail_admins', 'error_file'],
                'level': 'WARNING',
                'propagate': True,
           },
           'django.security': {
                'handlers': ['mail_admins', 'security_file'],
                'level': 'WARNING',
                'propagate': True,
           },
     }
}
```

There is a portion of the documentation that I'm still working on... you'll need to add an initial super user to the NEMO database. You'll have to open a terminal in the running Docker container, and issue the command `python manage.py createsuperuser`. Enter the user information (such as first name, last name, email, as normal. When you're prompted for a password, it doesn't matter what you enter because passwords aren't stored in NEMO's database. The user you create in the NEMO database will have to match up with an account that can be authenticated against in the LDAP server.

Diagnosing LDAP authentication issues in NEMO is particularly difficult (simply because authentication is tough to get right). This has prompted me to make this easier and add authentication diagnostic tools directly into NEMO. I plan to add these to the “nemo” executable that comes with the Python package, so you’ll be able to do this on the command line: `nemo query_public_key` and `nemo test_ldap_authentication`. This feature will be available in version 1.1.0, planned to release by February 6th.

Are you trying to open the website from a web browser running on the server? Or from a different computer? If you are trying to access the website from a different computer, then you may need to open a firewall hole in order to access port 8000. Furthermore, you'll need to specify the IP address instead of using `localhost`.

**Comment by hwagit** [comment]
Thank you for the reply! I'm sorry that I did not make it clear, but I just want to try out NEMO's features locally on my laptop, which is running Ubuntu 17.10, not on a server. Hence, I am a bit confused when you're saying that NEMO is apparently running fine on my computer (within Docker), even though I cannot access it in my browser. I am also sorry for my lack in experience with Docker.

**Comment by hwagit** [comment]
Connecting to a Django web app from outside a Docker container seems to be a common issue people have, although I cannot find the solution in my case after some time on Stackoverflow etc. As you say, the web app seems to run fine within the container, but I cannot access it locally via `localhost:8000`.

After successfully running the container using

```bash
> sudo docker run --publish 8000:8000 --volume /home/hakon/settings.py:/root/NEMO/settings.py --env "PYTHONPATH=/root/NEMO" --env "DJANGO_SETTINGS_MODULE=settings" dylanklomparens/nemo
```

I get

```bash
> sudo docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS              PORTS                    NAMES
60ad284eb5ef        dylanklomparens/nemo   "start_NEMO_in_Doc..."   About a minute ago   Up About a minute   0.0.0.0:8000->8000/tcp   compassionate_montalcini
```

And within the container

```bash
[root@60ad284eb5ef /]# curl -v localhost:8000
* About to connect() to localhost port 8000 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8000
> Accept: */*
> 
< HTTP/1.1 302 Found
< Server: gunicorn/19.7.1
< Date: Wed, 31 Jan 2018 18:39:49 GMT
< Connection: close
< Content-Type: text/html; charset=utf-8
< Location: /login/?next=/
< X-Frame-Options: SAMEORIGIN
< Vary: Cookie
< Content-Length: 0
< 
* Closing connection 0
```

But in my local host

```bash
> curl -v localhost:8000
* Rebuilt URL to: localhost:8000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.55.1
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

**Comment by clarkritchie** [comment]
@hwagit I agree -- it is definitely confusing. 😵 

Here is what I did:

Clone:

```
cd /some/dir
git clone git@github.com:usnistgov/NEMO.git nemo
```

Create a `settings.py` at the root of `/some/dir` with your customizations (thanks!) -- [here's mine](https://gist.github.com/clarkritchie/d262e21b47791e0cf3c012dc2899ea65).

Run:

```
docker run \
    --name nemo \
    -p 8000:8000 \
    --env "PYTHONPATH=/root/NEMO" \
    --env "DJANGO_SETTINGS_MODULE=settings" \
    --volume /some/dir/nemo:/root/NEMO \
    dylanklomparens/nemo
```

It sure seems like it's working.... there is [a lot of output](https://gist.github.com/clarkritchie/ca621c4246271387e599b6b4beaac80c), and stuff is running:
```
[root@a64321e9e417 /]# ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /bin/bash /usr/local/bin/start_NEMO_in_Docker.sh
   19 ?        S      0:00 /usr/bin/python3.6 /usr/bin/gunicorn NEMO.wsgi:applic
   22 ?        Sl     0:00 /usr/bin/python3.6 /usr/bin/gunicorn NEMO.wsgi:applic
   24 pts/0    Ss     0:00 /bin/bash
   43 pts/0    R+     0:00 ps ax
```

From my machine:
```
docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                      PORTS                    NAMES
a64321e9e417        dylanklomparens/nemo      "start_NEMO_in_Docke…"   4 minutes ago       Up 4 minutes                0.0.0.0:8000->8000/tcp   nemo
```

From the docker instance, I get 302:
```
[root@a64321e9e417 /]# curl -v -s http://localhost:8000
* About to connect() to localhost port 8000 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8000
> Accept: */*
>
< HTTP/1.1 302 Found
< Server: gunicorn/19.7.1
< Date: Tue, 27 Feb 2018 21:36:53 GMT
< Connection: close
< Content-Type: text/html; charset=utf-8
< Location: /login/?next=/
< X-Frame-Options: SAMEORIGIN
< Vary: Cookie
< Content-Length: 0
<
* Closing connection 0
```

...and 200:
```
[root@a64321e9e417 /]# curl -v -s http://localhost:8000/login/?next=/
* About to connect() to localhost port 8000 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /login/?next=/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8000
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: gunicorn/19.7.1
< Date: Tue, 27 Feb 2018 21:37:12 GMT
< Connection: close
< Content-Type: text/html; charset=utf-8
< X-Frame-Options: SAMEORIGIN
< Vary: Cookie
< Content-Length: 232
<
<!DOCTYPE html>
<html>
<head>
	<title>Authorization failed</title>
</head>
<body>
	You do not have a NEMO user account or your user account has been deactivated. Please contact the NanoFab User Office for assistance.
</body>
* Closing connection 0
```

But from localhost, I cannot get http://127.0.0.1/ or http://127.0.0.1/login or anything.
