### ISSUE TITLE
Consumables items decimal entries

### ISSUE THREAD

**Issue by nsieb** [usnistgov/NEMO#93]
Currently it is not possible to enter decimals for consumable withdraws (e.g., 5.6nm of gold).  This would provide a lot more flexibility in NEMO.

**Comment by rptmat57** [comment]
A good suggestion for this would be to use a different unit, in your case you could use angstrom instead of nanometer and change the price per nanometer to be per angstrom.

A few places depend on this being an integer like post usage questions and direct supply/material withdrawals.
So it might not be as straightforward as suggested. In order for this to work, we would probably need to add some kind of field on Consumable to specify if the quantity should be integer or float, or some kind of unit. (In post usage questions the type float or integer could be set pretty easily, but figuring out which one to use in the supply/material withdrawals is more complicated. We wouldn't want to allow decimals for things like gloves, glasses, boxes for example).

After further discussion, it was decided that this is not something we are willing to add at the moment, but if a good solution was proposed and contributed, we would strongly consider accepting it into NEMO.
