### ISSUE TITLE
Training entries

### ISSUE THREAD

**Issue by nsieb** [usnistgov/NEMO#95]
The method of entering training time in NEMO is a bit awkward.  It has to be done afterwards, which means that you need to use the tool under a staff account first and then enter the training time at the end.  I think it would be better if it is approached in a similar way to the staff charging system where you start a training session at the beginning and end it when you are finished.  Training appears to be the only usage in NEMO that you enter at the end of the session instead of during it.

**Comment by rptmat57** [comment]
Thank you for the suggestion, you bring up a good point.
Unfortunately, this would be a rather large undertaking, and is not a priority for our NanoFab at the moment since the current feature is sufficient for our needs.
However, if you or someone else wanted to develop that feature and willing to contribute it as a pull request, we would probably accept it into NEMO
